const constants = {
  DEFAULT_BUY_IN_COUNT: 0,

  DEFAULT_BUYIN_CASH: 100,
  DEFAULT_REBUY_CASH: 100,
  DEFAULT_BONUS_CASH: 200,

  DEFAULT_BUYIN_CHIPS: 18000,
  DEFAULT_REBUY_CHIPS: 18000,
  DEFAULT_BONUS_CHIPS: 0,

  DEFAULT_CURRENT_CASH_POOL: 0,
  DEFAULT_CURRENT_CHIP_POOL: 0,

  DEFAULT_BUBBLE_BOOL: false,
  DEFAULT_BUBBLE_SHARE: 1,

  DEFAULT_FIRST_PRIZE_FACTOR: 0.5,
  DEFAULT_SECOND_PRIZE_FACTOR: 0.3,
  DEFAULT_THIRD_PRIZE_FACTOR: 0.2,

  DEFAULT_COUNTDOWN_SECONDS: 1200,

  DEFAULT_PLAYER_LIST: [],
};
export default constants;
